### ISSUE TITLE
PHP 7 requires this tiny fix in SagCURLHTTPAdapter.php to make it work.

### ISSUE THREAD

**Issue by daverodal** [sbisbee/sag#100]
line 124

          $response->headers->$line[0] = ltrim($line[1]);

turns into 

          $response->headers->{$line[0]} = ltrim($line[1]);

this is probably not the best way to convey this.

**Comment by BlueM** [comment]
Just stumbled across the same issue and can confirm that this fixes the problem. Too bad it’s not yet integrated.

**Comment by jessemortenson** [comment]
:+1: for this change. Bitten by this bug as well. See "Changes to the handling of indirect variables...." on https://github.com/sbisbee/sag/issues/100

**Comment by sbisbee** [comment]
Apologies, I didn't realize people were still filing issues to this repo. I've posted a note that I haven't been maintaining this project for years. Closing ticket.
