### ISSUE TITLE
SSL with Cloudant Sag Error: cURL error #35 SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by Cyken-Zeraux** [sbisbee/sag#101]
I'm new to sag, and am experienced with cURL. I can get a proper response from Cloudant with useSSL(false), but when set to true, and setSSLCert(null), I receive this error:
~~~php
Sag Error: cURL error #35: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
~~~

This is completely reproducable with modifying the example file like so:
~~~php
  // We are going to get our page's content from Sag.
  $sag = new Sag('example.cloudant.com');
  $sag->setDatabase('example');
  $sag->useSSL(true);
  $sag->setSSLCert(null);
~~~

Tested on both Xaamp and Dreamhost.

Dreamhost settings:
PHP V: 5.6.10
cURL V: 7.22.0
OpenSSL/1.0.1
Apache: 2.2.31-2

Solutions attempted:
$opts[CURLOPT_SSL_VERIFYHOST] = false;
No effect

$opts[CURLOPT_SSL_CIPHER_LIST] = "ALL";
No effect

**Comment by Cyken-Zeraux** [comment]
Cloudant has confirmed its not a problem on their end. SAG can be confirmed to be an abandoned project when the most popular service it is supposed to facilitate is not securely supported or attempted to be fixed. Find a different library.

**Comment by sbisbee** [comment]
Apologies, I didn't realize people were still filing issues to this repo. I've posted a note that I haven't been maintaining this project for years. Closing ticket.
