### ISSUE TITLE
changePassword() in SagUserUtils not working

### ISSUE THREAD

**Issue by rgeraldporter** [sbisbee/sag#88]
Currently as it stands this function does not work. I have a pull request open that fixes this issue for CouchDB previous to v1.3.0; I'll now add an additional pull request that fixes this for v1.3.0+ users that use the PBKDF2 hashing method.

**Comment by mryellow** [comment]
Currently:
```
$doc->password_sha = sha1($newPassword + self::makeSalt());
```

Should be:
```
$doc->salt = self::makeSalt();
$doc->password_sha = sha1($newPassword . $doc->salt);
```

**Comment by sbisbee** [comment]
I appreciate the PR (I actually do, my response latency aside), but I have removed SagUserUtils from the project. It hardly ever worked and managing such things from the app was always awkward.
