### ISSUE TITLE
is this project abandoned?

### ISSUE THREAD

**Issue by dev-head** [sbisbee/sag#95]
No commits, no responses to issues, no pull requests merged... looks safe to consider it abandoned, no?

**Comment by sbisbee** [comment]
Correct, I am not working on Sag or CouchDB related projects these days. As far as I know the project still functions against recent versions of CouchDB and Cloudant, especially if you use the cURL based driver (it's also faster than native), but some "side" functionality like user management doesn't appear to comply with recent changes.

**Comment by BigBlueHat** [comment]
Yeah...wish I were, but my times going elsewhere. I'm mostly using PouchDB as my client-side CouchDB/Cloudant client now, and most of my server-side code is in Python for which I typically just use [requests](http://python-requests.org/).

@dev-head are you actively using Sag?

@sbisbee maybe we should update the readme to say we're looking for a new "owner"?

**Comment by sbisbee** [comment]
@dev-head FYI I just went through to clean up a bunch of the open tickets and PRs. They're dropped in master.
