### ISSUE TITLE
sag is no PHP < 5.5 friendly anymore

### ISSUE THREAD

**Issue by sempixel** [sbisbee/sag#98]
Because of PR https://github.com/sbisbee/sag/pull/86 and usage of [curl-reset()](http://php.net/manual/en/function.curl-reset.php) sag can't work anymore on PHP < 5.5

README needs to be updated if no revert is made.

Thanks!

**Comment by sbisbee** [comment]
Thank you, good catch. Updating the README as not even 5.5 is actively supported anymore (http://php.net/supported-versions.php), though of course it's mainline in Ubuntu.
